### ISSUE TITLE
Cracked windows apps and apks dont work

### ISSUE THREAD

**Issue by UltimateBoi** [Illegal-Services/Illegal_Services#13]
Both just are blank:
![image](https://user-images.githubusercontent.com/63293118/156841834-c6d80000-97e3-4f9f-8e2c-370d922503d7.png)
![image](https://user-images.githubusercontent.com/63293118/156841884-1d9958c3-1c0c-4ee6-a204-d3af34545d0a.png)

**Comment by Illegal-Services** [comment]
Hello I'm aware of that bug, I'm gonna fix that soon.
There are also a couple other category's with this problem.
The reason is bookmarks_parser.exe that contain a bug, i didn't searched what the problem is yet. Give me some days before a fix.

**Comment by UltimateBoi** [comment]
Cool thanks

In the meantime could you tell me where to manually get these resources?

**Comment by Illegal-Services** [comment]
The easier method would be to access this website:
https://illegal-services.github.io/Illegal_Services/IS.bookmarks.html
And scroll down or Ctrl+F for windows apps / apks

**Comment by Illegal-Services** [comment]
Other method to install the chrome IS extension (outdated but still working)

**Comment by Illegal-Services** [comment]
And other method to manually import IS bookmarks file

**Comment by Illegal-Services** [comment]
Also I'm prepairing to open a clean website ui so that's gonna soon be an other and good method, but I'm still working on it 💁🏼‍♂️

**Comment by UltimateBoi** [comment]
Where can i get the extension from?

**Comment by Illegal-Services** [comment]
Chrome web store

**Comment by UltimateBoi** [comment]
Ty

**Comment by Illegal-Services** [comment]
Hello, I've finally today fixed all known bugs, that, including that one in this build update:
[v6.1.2.0 - 09/03/2022](https://github.com/Illegal-Services/Illegal_Services/commit/96df4df50275da6f9bab5abf8a7bc7533f8b5e54#diff-30bc95eef2f06036bdea79fd3cda4006fe08f96c9861cc90060eb44f88d4338cR4942)

**Comment by Illegal-Services** [comment]
Followed with 2 bugfixes right after:
[v6.1.2.1 - 09/03/2022](https://github.com/Illegal-Services/Illegal_Services/commit/55e5ec7439d21c44fba8b7bb54f5fd4cf5735ae3#diff-30bc95eef2f06036bdea79fd3cda4006fe08f96c9861cc90060eb44f88d4338cR4033)
[v6.1.2.2 - 09/03/2022](https://github.com/Illegal-Services/Illegal_Services/commit/ffae1c47c623cfae77a6f94588f98ed1a6d6e37d#diff-30bc95eef2f06036bdea79fd3cda4006fe08f96c9861cc90060eb44f88d4338cR4946)
