### ISSUE TITLE
Youtube mods

### ISSUE THREAD

**Issue by UltimateBoi** [Illegal-Services/Illegal_Services#19]
The youtube mods page does not work.
All youtube vanced have been removed. Please update the youtube mods page.

**Comment by Illegal-Services** [comment]
Hello, please submit dead links so I can review them.
Also I cannot add more links or update because I'm not aware of more.

**Comment by UltimateBoi** [comment]
https://vancedapp.com/

**Comment by UltimateBoi** [comment]
https://youtubevanced.ru/

**Comment by Illegal-Services** [comment]
> https://vancedapp.com/

This is the official YouTube Vanced page, I'm not removing it cause it shows up alternatives

**Comment by Illegal-Services** [comment]
> https://youtubevanced.ru/

I can see that their download link isn't working, but the website is still up, I don't know if I should.

**Comment by UltimateBoi** [comment]
delete it, it dosent give anything for it to be there. Also vanced no longer works on whatever page you download it from.

**Comment by Illegal-Services** [comment]
> the alternatives arent even youtube! it is literally 2 browsers!

If you are looking for alternatives:
![firefox_2022-07-12_21-30](https://user-images.githubusercontent.com/62464560/178578325-ffe64f02-01f8-40b6-8c92-7a20f67f215c.png)

**Comment by UltimateBoi** [comment]
it only gives an ios option and it is in the android section.

**Comment by Illegal-Services** [comment]
> delete it, it dosent give anything for it to be there. Also vanced no longer works on whatever page you download it from.

It does work on my own mobile ...

**Comment by UltimateBoi** [comment]
hmm send the one youre using.

**Comment by Illegal-Services** [comment]
> hmm send the one youre using.

We are in IS "issues" from GitHub, this place doesn't belong for custom helping of the users.

**Comment by UltimateBoi** [comment]
sorry.

**Comment by Illegal-Services** [comment]
I suggest you to join our Telegram to keep this conversation, https://t.me/illegal_services_forum
