### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yqevi** [Illegal-Services/Illegal_Services#21]
So my friend found this guy who is a child predator on roblox, He tries to have e sex and if theyre in his area meet with them and have sex, he is 20 years old and my friend is a minor and he knew that and the child pretator said that he would spank and fuck my friend in the ass. And we dont really want him to actually do it to people irl so were just trying to get him in trouble by contacting his parents and family and if he has a gf or something tell her, But we have like no info on him and we kinda wanna find out his moms name and phone number and stuff, Will this do such?

**Comment by Illegal-Services** [comment]
Hello, if you want to take down a sexual predator, the only thing you have to do is take screenshot evidence and report the user to the video game and to an organism law enforcement, such as the police.
