### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moti477** [Illegal-Services/Illegal_Services#22]
Hello, I get this error how can I fix it?
![image](https://user-images.githubusercontent.com/75843171/196783011-cbd6ee71-a13c-46b2-bfd8-4bd159189259.png)

**Comment by Illegal-Services** [comment]
Hello and thank you for reaching me with an issue report.

Can you download the [latest version](https://github.com/Illegal-Services/Illegal_Services/archive/refs/heads/main.zip) and try again please?
I believe the reason you got this error message is that recently I've been upgrading the source code managing the git proxys for the raw wet requests. You screenshot being one.
Unfortunately I had pushed 2 versions online ([v6.1.7.6 - 17/10/2022](https://github.com/Illegal-Services/Illegal_Services/commit/2a0349be8544f13ad24dd1f4aa8815bfdb15ed9c) to [v6.1.8.0 - 21/10/2022](https://github.com/Illegal-Services/Illegal_Services/commit/56a62d7a9bc6e623a7255bdd1422841494ba4fe5)) updates containing a broken algorithm.

My apologizes for answering you late.
My mails from GitHub where sent for a while on my spam folder and I only noticed it today!

**Comment by Illegal-Services** [comment]
No answers given back from sender, probably fixed by the time?
