### ISSUE TITLE
V6.1 won't install because it has a virus

### ISSUE THREAD

**Issue by SoftieIsVibing** [Illegal-Services/Illegal_Services#28]
![image](https://user-images.githubusercontent.com/65833167/219857813-08b8c2a1-2ba3-4c12-9af0-277ed3b0b030.png)
This happens whenever i try to install it and shortly after my antivirus goes off saying it detected malware
Is this a false report or smth?

**Comment by Illegal-Services** [comment]
Duplicate of other closer issues
