### ISSUE TITLE
i am not saying it's a malware or trojan but VIRUS TOTAL IS!

### ISSUE THREAD

**Issue by Barrle** [Illegal-Services/Illegal_Services#35]

**Comment by Illegal-Services** [comment]
man it's an open source project, if you don't trusth, read the code, idk what you want from me you stealing my time!

**Comment by Illegal-Services** [comment]
read that faq

**Comment by Illegal-Services** [comment]
wtf sus you don't know how to read do you???

**Comment by Illegal-Services** [comment]
![firefox_2023-10-24_14-08](https://github.com/Illegal-Services/Illegal_Services/assets/62464560/232d25cb-2b5d-4b87-9cad-ed5416efa8af)

**Comment by Illegal-Services** [comment]
https://github.com/Illegal-Services/Illegal_Services/blob/source/Illegal_Services.bat

**Comment by Illegal-Services** [comment]
as I said, source code is literally open source.
