### ISSUE TITLE
Colour on text not working and displaying the codes instead

### ISSUE THREAD

**Issue by UltimateBoi** [Illegal-Services/Illegal_Services#51]
![image](https://github.com/Illegal-Services/Illegal_Services/assets/63293118/24e24b29-d698-4e70-a3a3-bf307533dd0f)

**Comment by Illegal-Services** [comment]
not an issue from my side

**Comment by Illegal-Services** [comment]
its your computer

**Comment by UltimateBoi** [comment]
![image](https://github.com/Illegal-Services/Illegal_Services/assets/63293118/5a6bd333-53d8-44c1-a6d1-84b39ea2224f)

**Comment by UltimateBoi** [comment]
> its your computer

any fix?

**Comment by Illegal-Services** [comment]
Nop

**Comment by UltimateBoi** [comment]
whaa? it dont even open now. just says access denied and the colour code
