### ISSUE TITLE
Internet access

### ISSUE THREAD

**Issue by FearlessOfficial** [Illegal-Services/Illegal_Services#54]
I think it should be bug
@Illegal-Services 
**error msg:** 

**From** -- IIIegal_Services

**MSG -- "Your Internet access appears to be offline.  You must activate Internet and try again"** 

funny think i have Internet on ...

error img - - - -    ![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/f2338c3c-e18e-4a95-8998-2914ec128f9e)

**Comment by Illegal-Services** [comment]
Hello, which option did you select in the settings to get that error message? I'd assume it's from option 20 ?

**Comment by FearlessOfficial** [comment]
> Hello, which option did you select in the settings to get that error message? I'd assume it's from option 19 or 20?

19

**Comment by FearlessOfficial** [comment]
> Hello, which option did you select in the settings to get that error message? I'd assume it's from option 19 or 20?

rn i can't even open any stuff when i run like apps and cracked or someting is says it again but my network is on, no vpn, no proxy or secure dns

**Comment by FearlessOfficial** [comment]
> > Hello, which option did you select in the settings to get that error message? I'd assume it's from option 19 or 20?
> 
> rn i can't even open any stuff when i run like apps and cracked or someting is says it again but my network is on, no vpn, no proxy or secure dns

when i got the newer version

**Comment by Illegal-Services** [comment]
Mhmm, can you give me your is version in the launcher / main menu and can you show me your registry settings from IS app ?

**Comment by FearlessOfficial** [comment]
> Mhmm, can you give me your IS version in the launcher / main menu and can you show me your registry settings from IS app ?

alright

**Comment by Illegal-Services** [comment]
I believe you are stuck on an older version with a proxy down

**Comment by FearlessOfficial** [comment]
> I believe you are stuck on an older version with a proxy down

correct

**Comment by FearlessOfficial** [comment]
> I believe you are stuck on an older version with a proxy down

![image](https://github.com/Illegal-Services/Illegal_Services/assets/152205968/9184a961-b2a5-4bb1-a25e-b12d1af1a374)

**Comment by FearlessOfficial** [comment]
> > I believe you are stuck on an older version with a proxy down
> 
> ![image](https://private-user-images.githubusercontent.com/152205968/289279589-9184a961-b2a5-4bb1-a25e-b12d1af1a374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzQ4MzAsIm5iZiI6MTcwMjEzNDUzMCwicGF0aCI6Ii8xNTIyMDU5NjgvMjg5Mjc5NTg5LTkxODRhOTYxLWIyYTUtNGJiMS1hMjVlLWIxMmQxYWYxYTM3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQxNTA4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTAzZTA1N2I1N2NlMjY5ZjI3ZjA3M2JmZDEwZjA1MWJmZjJhNThjZjQxY2YxYjNjNzcyOGUwY2Q5N2MyZDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xuc5uNQpIIlh7DkpV1qU46SkQsRn0_QN_E2NcOwa1nU)

I got version - --    v6.1.9.5

**Comment by Illegal-Services** [comment]
Alright you can just reinstall then and problem will be fixed

**Comment by Illegal-Services** [comment]
wait what- you are talking with Elon Musk? Who are you :0

**Comment by FearlessOfficial** [comment]
> Alright you can just reinstall then and problem will be fixed

alright

**Comment by FearlessOfficial** [comment]
> wait what- you are talking with Elon Musk? Who are you :0

xd :D yes i am

**Comment by Illegal-Services** [comment]
that's crazy

**Comment by Illegal-Services** [comment]
Also Illegal Services app is pretty much forgotten, if you want something better to use, I recommend reading this page:
https://illegal-services.github.io/Illegal_Services/tutorial.html

**Comment by FearlessOfficial** [comment]
> Also Illegal Services app is pretty much forgotten, if you want something better to use, I recommend reading this page: https://illegal-services.github.io/Illegal_Services/tutorial.html

alright thanks you :>
Have a nice day

**Comment by Illegal-Services** [comment]
have a nice day, thanks
