### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Stormtrooper0744** [Illegal-Services/Illegal_Services#6]
When I tried to install It,Microsoft defender thinked  that illegal services was Trojan

**Comment by Illegal-Services** [comment]
Hi. This question is already answered in Illegal Services F.A.Q:
https://illegal-services.github.io/Illegal_Services/faq.html

**Comment by Stormtrooper0744** [comment]
Thank you

**Comment by Nexuzzzz** [comment]
> Hi. This question is already answered in Illegal Services F.A.Q: https://illegal-services.github.io/Illegal_Services/faq.html
> 
> 💎 Why Illegal Services is detected by many antiviruses ? The source code is converted from batch to executable using https://www.abyssmedia.com/quickbfc/ This conversion process leads to believe that it is a virus.

why is it converted tho?

**Comment by Illegal-Services** [comment]
@Nexuzzzz
1. Administrator manifest obligatory under IS executable.
2. Executable with an icon.
