### ISSUE TITLE
Unicode characters missing.

### ISSUE THREAD

**Issue by Illegal-Services** [Illegal-Services/Illegal_Services#7]
![Sans titre-4](https://user-images.githubusercontent.com/62464560/150379359-17b93126-73cc-46e2-b86f-55715dd95b5d.png)

![Sans titre-5](https://user-images.githubusercontent.com/62464560/150379366-659b2ac7-0614-4d65-b680-babb9af0e328.png)
 
I think the pictures speak for themselves.

~~I currently have no information on how this happens and therefore, how to fix it.~~ [#7 (comment)](https://github.com/Illegal-Services/Illegal_Services/issues/7#issuecomment-1023129789)
This bug happen together with issue: ['find' process blocking/freezing Illegal Services. #8](https://github.com/Illegal-Services/Illegal_Services/issues/8).

**Comment by Illegal-Services** [comment]
Contrary to what I say, Illegal Services latest version is unfortunately not compatible anymore on Windows 7. (may be the same for Windows 8/8.1.)
This is from the recent transformation of my source of the Windows 1252 encoding to UTF-8.
See these Github issue pages for more details https://github.com/illegal-services/illegal_services/issues/7, https://github.com/illegal-services/illegal_services/issues/8

For the moment I am looking for a way to find a solution to this problem, waiting for the next V6.0.0.0 for a possible fix or abandonment of the support for Windows 7. (can be the same for Windows 8/8.1. )

For the moment, the best you can do if your concerned in this issue is to downgrade your IS version to this release:
https://github.com/illegal-services/illegal_services/releases/tag/v5.8
And manually install the latest build update for the v5.8 by replacing those files in is installation path:
https://raw.githubusercontent.com/illegal-services/illegal_services/6E03D4EC43257B7A6700B54657907E48C424364B/ILLEGAL_Services.exe
https://raw.githubusercontent.com/illegal-services/illegal_services/6E03D4EC43257B7A6700B54657907E48C424364B/Changelog.txt

**Comment by agamsol** [comment]
### your curl installation, is delivered from Microsoft so go complain to them.

That's what he said.

**Comment by Illegal-Services** [comment]
Fixed in v6.0.0.0; Removed Widows 7, 8, 8.1 support.
